---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seaweedfs-s3-config
  namespace: kubeflow
data:
  s3.json: |
    {
      "identities": [
        {
          "name": "kubeflow-pipeline",
          "credentials": [
            {
              "accessKey": "${ACCESS_KEY}",
              "secretKey": "${SECRET_KEY}"
            }
          ],
          "actions": [
            "Read:*/*",
            "Write:*/*",
            "List:*",
            "Tagging:*/*"
          ]
        }
      ]
    }
  startup-script.sh: |
    #!/bin/sh
    
    # Get credentials from the secret
    ACCESS_KEY=$(cat /credentials/access_key)
    SECRET_KEY=$(cat /credentials/secret_key)
    
    # Replace placeholders with actual credentials
    sed -i "s/\${ACCESS_KEY}/$ACCESS_KEY/g" /config/s3.json
    sed -i "s/\${SECRET_KEY}/$SECRET_KEY/g" /config/s3.json
    
    echo "SeaweedFS S3 configuration initialized"
  audit-log-config.json: |
    {
      "enabled": true,
      "filePath": "/tmp/s3_audit.log",
      "rotateSize": "100M",
      "maxBackups": 7
    }
